#!/bin/bash
source ../userpass
#curl -s --url "http://127.0.0.1:6650" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"BTC\",\"ipaddr\":\"173.212.225.176\",\"port\":50001}"
curl -s --url "http://127.0.0.1:6650" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"KMD\",\"ipaddr\":\"electrum1.cipig.net\",\"port\":10001}"
curl -s --url "http://127.0.0.1:6650" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"KMD\",\"ipaddr\":\"electrum2.cipig.net\",\"port\":10001}"
curl -s --url "http://127.0.0.1:6650" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"SNG\",\"ipaddr\":\"45.77.254.232\",\"port\":10001}"
curl -s --url "http://127.0.0.1:6650" --data "{\"userpass\":\"$userpass\",\"method\":\"electrum\",\"coin\":\"BTC\",\"ipaddr\":\"128.199.233.38\",\"port\":10001}"
