#!/bin/bash
source ../userpass
source passphrase
curl -s --url "http://127.0.0.1:6650" --data "{\"userpass\":\"$userpass\",\"method\":\"inventory\",\"coin\":\"KMD\",\"reset\":1,\"passphrase\":\"$passphrase\"}"
