#!/bin/bash
source ../userpass
echo "usage: ./secretaddresses 'passphrase'"

curl -s --url "http://127.0.0.1:6650" --data "{\"userpass\":\"$userpass\",\"method\":\"secretaddresses\",\"num\":16,\"passphrase\":\"$1\"}"

